// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.github.qilihui.usercenter.grpc;

public final class Base {
    private Base() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_grpc_TestRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_grpc_TestRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_grpc_TestResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_grpc_TestResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\nbase.proto\022\004grpc\"\037\n\013TestRequest\022\020\n\010use" +
                        "rName\030\001 \001(\t\"\"\n\014TestResponse\022\022\n\nserverDat" +
                        "e\030\001 \001(\t2A\n\013TestService\0222\n\007getDate\022\021.grpc" +
                        ".TestRequest\032\022.grpc.TestResponse\"\000B,\n\"co" +
                        "m.github.qilihui.usercenter.grpcB\004BaseP\001" +
                        "b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_grpc_TestRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_grpc_TestRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_grpc_TestRequest_descriptor,
                new String[]{"UserName",});
        internal_static_grpc_TestResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_grpc_TestResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_grpc_TestResponse_descriptor,
                new String[]{"ServerDate",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
