// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.github.qilihui.usercenter.grpc;

public interface TestResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:grpc.TestResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string serverDate = 1;</code>
     */
    String getServerDate();

    /**
     * <code>optional string serverDate = 1;</code>
     */
    com.google.protobuf.ByteString
    getServerDateBytes();
}
