// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.github.qilihui.usercenter.grpc;

public interface TestRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:grpc.TestRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userName = 1;</code>
     */
    String getUserName();

    /**
     * <code>optional string userName = 1;</code>
     */
    com.google.protobuf.ByteString
    getUserNameBytes();
}
